# Generated by Django 5.0.4 on 2024-05-08 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_content_alter_article_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="cover_image",
            new_name="cover_image_url",
        ),
        migrations.AlterField(
            model_name="article",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.topic",
            ),
        ),
    ]
